<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>faaba611-dfac-4f84-8965-895a18a35b8b</elementGuidId>
    <imagePath></imagePath>
    <name>link_AirConditioners</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/s/?_encoding=UTF8&amp;bbn=81107432031&amp;rh=n%3A81107432031%2Cp_85%3A10440599031&amp;pd_rd_w=iTgFH&amp;content-id=amzn1.sym.58c90a12-100b-4a2f-8e15-7c06f1abe2be&amp;pf_rd_p=58c90a12-100b-4a2f-8e15-7c06f1abe2be&amp;pf_rd_r=2A12C74F4K7MZWT2R9HS&amp;pd_rd_wg=iJK8J&amp;pd_rd_r=7b0e743b-fe8c-485a-be1b-07c5e2eab2dd&amp;ref_=pd_hp_d_atf_unk') and equals(@text,'Air conditioners')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="ACs"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/s/?_encoding=UTF8&amp;bbn=81107432031&amp;rh=n%3A81107432031%2Cp_85%3A10440599031&amp;pd_rd_w=iTgFH&amp;content-id=amzn1.sym.58c90a12-100b-4a2f-8e15-7c06f1abe2be&amp;pf_rd_p=58c90a12-100b-4a2f-8e15-7c06f1abe2be&amp;pf_rd_r=2A12C74F4K7MZWT2R9HS&amp;pd_rd_wg=iJK8J&amp;pd_rd_r=7b0e743b-fe8c-485a-be1b-07c5e2eab2dd&amp;ref_=pd_hp_d_atf_unk</value>
        <webElementGuid>bb88ba4e-f2ba-49f8-ae42-3ec1acc2cec8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Air conditioners</value>
        <webElementGuid>bb88ba4e-f2ba-49f8-ae42-3ec1acc2cec8</webElementGuid>
    </webElementProperties>
</WebElementEntity>