<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a7d831a1-3868-49ff-99c0-9c219bb5d36f</elementGuidId>
    <imagePath></imagePath>
    <name>link_boAt</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[6]/div[1]/div[2]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/s/?_encoding=UTF8&amp;bbn=1388921031&amp;rh=n%3A1388921031%2Cp_89%3AboAt&amp;pd_rd_w=ex6RX&amp;content-id=amzn1.sym.82b20790-8877-4d70-8f73-9d8246e460aa&amp;pf_rd_p=82b20790-8877-4d70-8f73-9d8246e460aa&amp;pf_rd_r=MKYAGNB81VWYZFA98PZZ&amp;pd_rd_wg=tysxM&amp;pd_rd_r=8a396f80-bb34-4d1d-9150-c1704dbbea39&amp;ref_=pd_hp_d_atf_unk') and equals(@text,'Starting ₹249 | boAt')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="boAt"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/s/?_encoding=UTF8&amp;bbn=1388921031&amp;rh=n%3A1388921031%2Cp_89%3AboAt&amp;pd_rd_w=ex6RX&amp;content-id=amzn1.sym.82b20790-8877-4d70-8f73-9d8246e460aa&amp;pf_rd_p=82b20790-8877-4d70-8f73-9d8246e460aa&amp;pf_rd_r=MKYAGNB81VWYZFA98PZZ&amp;pd_rd_wg=tysxM&amp;pd_rd_r=8a396f80-bb34-4d1d-9150-c1704dbbea39&amp;ref_=pd_hp_d_atf_unk</value>
        <webElementGuid>7c7e3121-54d2-43c2-888f-abc7e5182be3</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Starting ₹249 | boAt</value>
        <webElementGuid>7c7e3121-54d2-43c2-888f-abc7e5182be3</webElementGuid>
    </webElementProperties>
</WebElementEntity>