<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>76ed46f0-2dec-41e2-a96c-e200aa83f2e7</elementGuidId>
    <imagePath></imagePath>
    <name>link_CustomerService</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/header[1]/div[1]/div[4]/div[2]/div[2]/div[1]/a[8]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/gp/help/customer/display.html?nodeId=200507590&amp;ref_=nav_cs_help') and equals(@text,'Customer Service')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Customer Service"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/gp/help/customer/display.html?nodeId=200507590&amp;ref_=nav_cs_help</value>
        <webElementGuid>7c7e3121-54d2-43c2-888f-abc7e5182be3</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Customer Service</value>
        <webElementGuid>7c7e3121-54d2-43c2-888f-abc7e5182be3</webElementGuid>
    </webElementProperties>
</WebElementEntity>