<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>de5fff2c-9e05-4cd2-94a9-17d467d79d3c</elementGuidId>
    <imagePath></imagePath>
    <name>link_Books</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[6]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/gp/movers-and-shakers/books/ref=zg_bsms_nav_books_0') and equals(@text,'Books')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=treeitem[name="Books"i] &gt;&gt; internal:role=link</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/gp/movers-and-shakers/books/ref=zg_bsms_nav_books_0</value>
        <webElementGuid>bb88ba4e-f2ba-49f8-ae42-3ec1acc2cec8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Books</value>
        <webElementGuid>bb88ba4e-f2ba-49f8-ae42-3ec1acc2cec8</webElementGuid>
    </webElementProperties>
</WebElementEntity>