<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c15fb535-c092-43f5-8b25-ab0140d7ce00</elementGuidId>
    <imagePath></imagePath>
    <name>link_CarlingtonWatch</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/ol[1]/li[1]/div[1]/div[2]/span[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/Carlington-Analog-Digital-Chronograph-Water-Resistant-Shock-Resistant/dp/B0CF5FSS8J/ref=zg_bsms_c_watches_d_sccl_1/261-4519587-9490508?pd_rd_w=jqdfF&amp;content-id=amzn1.sym.cde02f8b-0594-439d-9e93-f4cced7ce3ce&amp;pf_rd_p=cde02f8b-0594-439d-9e93-f4cced7ce3ce&amp;pf_rd_r=FEMN87KM3BMDGD5XYM3Z&amp;pd_rd_wg=w94bP&amp;pd_rd_r=e6a5dbdd-b058-4c5b-b495-3729dfe3e22e&amp;pd_rd_i=B0DZ2R7QB3&amp;psc=1')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>li &gt;&gt; internal:has-text="#1Sales rank: 125 (previously"i &gt;&gt; a &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/Carlington-Analog-Digital-Chronograph-Water-Resistant-Shock-Resistant/dp/B0CF5FSS8J/ref=zg_bsms_c_watches_d_sccl_1/261-4519587-9490508?pd_rd_w=jqdfF&amp;content-id=amzn1.sym.cde02f8b-0594-439d-9e93-f4cced7ce3ce&amp;pf_rd_p=cde02f8b-0594-439d-9e93-f4cced7ce3ce&amp;pf_rd_r=FEMN87KM3BMDGD5XYM3Z&amp;pd_rd_wg=w94bP&amp;pd_rd_r=e6a5dbdd-b058-4c5b-b495-3729dfe3e22e&amp;pd_rd_i=B0DZ2R7QB3&amp;psc=1</value>
        <webElementGuid>e26a3569-a0d4-427f-b52f-3eafd33530cb</webElementGuid>
    </webElementProperties>
</WebElementEntity>