<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0ec3f19f-fc06-47c4-9ccb-4df29b8df628</elementGuidId>
    <imagePath></imagePath>
    <name>link_SmartTVs</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[2]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/b/ref=s9_acss_bw_cg_revamp1_3b1_w?node=12516994031&amp;pf_rd_m=AT95IG9ONZD7S&amp;pf_rd_s=merchandised-search-6&amp;pf_rd_r=5KZC922464XN2PA02TB5&amp;pf_rd_t=101&amp;pf_rd_p=8721cc57-3a43-4ec9-85f4-4f2a55b51e9d&amp;pf_rd_i=13773797031')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Smart TVs"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/b/ref=s9_acss_bw_cg_revamp1_3b1_w?node=12516994031&amp;pf_rd_m=AT95IG9ONZD7S&amp;pf_rd_s=merchandised-search-6&amp;pf_rd_r=5KZC922464XN2PA02TB5&amp;pf_rd_t=101&amp;pf_rd_p=8721cc57-3a43-4ec9-85f4-4f2a55b51e9d&amp;pf_rd_i=13773797031</value>
        <webElementGuid>7c7e3121-54d2-43c2-888f-abc7e5182be3</webElementGuid>
    </webElementProperties>
</WebElementEntity>