<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f2ea5040-c299-4366-b1c8-f58bdcbd0dc3</elementGuidId>
    <imagePath></imagePath>
    <name>link_Fashion</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[2]/div[3]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/gp/bestsellers/boost/10894226031/ref=zg_bs_nav_boost_2_10894228031') and equals(@text,'Fashion')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=treeitem[name="Fashion"i] &gt;&gt; internal:role=link</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/gp/bestsellers/boost/10894226031/ref=zg_bs_nav_boost_2_10894228031</value>
        <webElementGuid>bb88ba4e-f2ba-49f8-ae42-3ec1acc2cec8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Fashion</value>
        <webElementGuid>bb88ba4e-f2ba-49f8-ae42-3ec1acc2cec8</webElementGuid>
    </webElementProperties>
</WebElementEntity>