<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9789484f-4aa9-4bfc-8027-c488f569ed9f</elementGuidId>
    <imagePath></imagePath>
    <name>link_ClothingAndAccessories</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[7]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/gp/movers-and-shakers/apparel/ref=zg_bsms_nav_apparel_0_books') and equals(@text,'Clothing &amp; Accessories')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Clothing &amp; Accessories"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/gp/movers-and-shakers/apparel/ref=zg_bsms_nav_apparel_0_books</value>
        <webElementGuid>bb88ba4e-f2ba-49f8-ae42-3ec1acc2cec8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Clothing &amp; Accessories</value>
        <webElementGuid>bb88ba4e-f2ba-49f8-ae42-3ec1acc2cec8</webElementGuid>
    </webElementProperties>
</WebElementEntity>