<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7f48407d-a444-44e5-b883-584da579de56</elementGuidId>
    <imagePath></imagePath>
    <name>link_AmazonRenewed</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/gp/movers-and-shakers/amazon-renewed/ref=zg_bsms_nav_amazon-renewed_0_boost') and equals(@text,'Amazon Renewed')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Amazon Renewed"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/gp/movers-and-shakers/amazon-renewed/ref=zg_bsms_nav_amazon-renewed_0_boost</value>
        <webElementGuid>bb88ba4e-f2ba-49f8-ae42-3ec1acc2cec8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Amazon Renewed</value>
        <webElementGuid>bb88ba4e-f2ba-49f8-ae42-3ec1acc2cec8</webElementGuid>
    </webElementProperties>
</WebElementEntity>