<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b2d8c328-42cb-420c-ab5f-301410293111</elementGuidId>
    <imagePath></imagePath>
    <name>link_DisruptiveInnovations</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/gp/bestsellers/boost/14091238031/ref=zg_bs_nav_boost_2_10894251031') and equals(@text,'Disruptive Innovations')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Disruptive Innovations"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/gp/bestsellers/boost/14091238031/ref=zg_bs_nav_boost_2_10894251031</value>
        <webElementGuid>e26a3569-a0d4-427f-b52f-3eafd33530cb</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Disruptive Innovations</value>
        <webElementGuid>e26a3569-a0d4-427f-b52f-3eafd33530cb</webElementGuid>
    </webElementProperties>
</WebElementEntity>