<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>233a0fe2-23f4-41c5-b5c3-4c3cf1948655</elementGuidId>
    <imagePath></imagePath>
    <name>link_Baby</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/gp/new-releases/apparel/1953148031/ref=zg_bsnr_nav_apparel_1') and equals(@text,'Baby')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=treeitem[name="Baby"i] &gt;&gt; internal:role=link</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/gp/new-releases/apparel/1953148031/ref=zg_bsnr_nav_apparel_1</value>
        <webElementGuid>e26a3569-a0d4-427f-b52f-3eafd33530cb</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Baby</value>
        <webElementGuid>e26a3569-a0d4-427f-b52f-3eafd33530cb</webElementGuid>
    </webElementProperties>
</WebElementEntity>