<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9c017a17-8091-4691-ab76-f9d5ec8d42a8</elementGuidId>
    <imagePath></imagePath>
    <name>link_IndianLanguageEBooks</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/header[1]/div[1]/div[6]/div[1]/a[9]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/b/?ie=UTF8&amp;node=10837926031&amp;ref_=sv_kinc_8') and equals(@text,'Indian language eBooks')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Indian language eBooks, You"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/b/?ie=UTF8&amp;node=10837926031&amp;ref_=sv_kinc_8</value>
        <webElementGuid>7c7e3121-54d2-43c2-888f-abc7e5182be3</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Indian language eBooks</value>
        <webElementGuid>7c7e3121-54d2-43c2-888f-abc7e5182be3</webElementGuid>
    </webElementProperties>
</WebElementEntity>