<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e8ce817c-b3b4-4bee-8047-c434f6c4b62f</elementGuidId>
    <imagePath></imagePath>
    <name>link_QtsyDapperSherwani</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/span[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/Qtsy-Cotton-Ethnic-Sherwani-Maroon/dp/B07JB5TGN1/ref=zg_bs_g_16085638031_d_sccl_1/261-4519587-9490508?psc=1')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#p13n-asin-index-0 a &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/Qtsy-Cotton-Ethnic-Sherwani-Maroon/dp/B07JB5TGN1/ref=zg_bs_g_16085638031_d_sccl_1/261-4519587-9490508?psc=1</value>
        <webElementGuid>e26a3569-a0d4-427f-b52f-3eafd33530cb</webElementGuid>
    </webElementProperties>
</WebElementEntity>