<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e0a9a1a4-1e4b-4bc5-b712-458c8012f92b</elementGuidId>
    <imagePath></imagePath>
    <name>link_SeeAllDevicesWithAlexa</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[2]/div[2]/ul[2]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/gp/browse.html?node=14156834031&amp;ref_=nav_em__shopall_catpage_0_2_2_2') and equals(@text,'See all devices with Alexa')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="See all devices with Alexa"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/gp/browse.html?node=14156834031&amp;ref_=nav_em__shopall_catpage_0_2_2_2</value>
        <webElementGuid>7c7e3121-54d2-43c2-888f-abc7e5182be3</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>See all devices with Alexa</value>
        <webElementGuid>7c7e3121-54d2-43c2-888f-abc7e5182be3</webElementGuid>
    </webElementProperties>
</WebElementEntity>