<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>bb1de9aa-99a3-469c-aa89-f326e1222be6</elementGuidId>
    <imagePath></imagePath>
    <name>link_SingleProduct</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/span[1]/div[1]/div[1]/div[1]/span[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/sspa/click?ie=UTF8&amp;spc=MTo2NzkwMzY4MjUxNDU3OTkwOjE3NDExNzU4MzQ6c3BfYXRmX2Jyb3dzZTozMDAxNjk3NzgwODcxMzI6OjA6Og&amp;url=%2FGodrej-Convertible-Split-AC-12TINV3R32-GWA%2Fdp%2FB0BN37ZCF7%2Fref%3Dsr_1_1_sspa%3F_encoding%3DUTF8%26content-id%3Damzn1.sym.58c90a12-100b-4a2f-8e15-7c06f1abe2be%26dib%3DeyJ2IjoiMSJ9.LpujZ4uISPUK8sa_6yNGVTLp2_seTR9samDUOPD7O25xlexzdSA-BOlKZoDoZTUKyNiOMggUFM4dmvCDvgwRrJ0520p0LoTi57Xz1ZJK4iI2Pf790XPfVTTw4PGqE3OB3kVxveD7fO6PJnKOtRdH2-HVewM_-qrtqpc3l8YhS004AlhRzA1fncRY0_0FFliYjbqZkUx_s7lj-07hF6SveS6s1soNancTCqDSvhzFwqBTi5S4Z_DdKC9b4tSZaRD3-f6mD_iEcwJ-Np9Z8L7SnYnzmauAWGY0X4jCHpik6lQ.f7eGFDJut4KoVK49evvwYyfYOy-Pv6eCWXeRyUMYHfk%26dib_tag%3Dse%26pd_rd_r%3D7b0e743b-fe8c-485a-be1b-07c5e2eab2dd%26pd_rd_w%3DiTgFH%26pd_rd_wg%3DiJK8J%26qid%3D1741175834%26refinements%3Dp_85%253A10440599031%26rps%3D1%26s%3Dkitchen%26sr%3D1-1-spons%26sp_csd%3Dd2lkZ2V0TmFtZT1zcF9hdGZfYnJvd3Nl%26psc%3D1')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.rush-component &gt; .a-link-normal &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/sspa/click?ie=UTF8&amp;spc=MTo2NzkwMzY4MjUxNDU3OTkwOjE3NDExNzU4MzQ6c3BfYXRmX2Jyb3dzZTozMDAxNjk3NzgwODcxMzI6OjA6Og&amp;url=%2FGodrej-Convertible-Split-AC-12TINV3R32-GWA%2Fdp%2FB0BN37ZCF7%2Fref%3Dsr_1_1_sspa%3F_encoding%3DUTF8%26content-id%3Damzn1.sym.58c90a12-100b-4a2f-8e15-7c06f1abe2be%26dib%3DeyJ2IjoiMSJ9.LpujZ4uISPUK8sa_6yNGVTLp2_seTR9samDUOPD7O25xlexzdSA-BOlKZoDoZTUKyNiOMggUFM4dmvCDvgwRrJ0520p0LoTi57Xz1ZJK4iI2Pf790XPfVTTw4PGqE3OB3kVxveD7fO6PJnKOtRdH2-HVewM_-qrtqpc3l8YhS004AlhRzA1fncRY0_0FFliYjbqZkUx_s7lj-07hF6SveS6s1soNancTCqDSvhzFwqBTi5S4Z_DdKC9b4tSZaRD3-f6mD_iEcwJ-Np9Z8L7SnYnzmauAWGY0X4jCHpik6lQ.f7eGFDJut4KoVK49evvwYyfYOy-Pv6eCWXeRyUMYHfk%26dib_tag%3Dse%26pd_rd_r%3D7b0e743b-fe8c-485a-be1b-07c5e2eab2dd%26pd_rd_w%3DiTgFH%26pd_rd_wg%3DiJK8J%26qid%3D1741175834%26refinements%3Dp_85%253A10440599031%26rps%3D1%26s%3Dkitchen%26sr%3D1-1-spons%26sp_csd%3Dd2lkZ2V0TmFtZT1zcF9hdGZfYnJvd3Nl%26psc%3D1</value>
        <webElementGuid>bb88ba4e-f2ba-49f8-ae42-3ec1acc2cec8</webElementGuid>
    </webElementProperties>
</WebElementEntity>