<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a32fc61e-8591-4018-8101-8abf5c2337a5</elementGuidId>
    <imagePath></imagePath>
    <name>link_MeetName</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[2]/div[2]/ul[2]/li[6]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/gp/browse.html?node=14172468031&amp;ref_=nav_em__shopall_meetalexa_0_2_2_4') and equals(@text,'Meet {{name}}')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/gp/browse.html?node=14172468031&amp;ref_=nav_em__shopall_meetalexa_0_2_2_4</value>
        <webElementGuid>e26a3569-a0d4-427f-b52f-3eafd33530cb</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Meet {{name}}</value>
        <webElementGuid>e26a3569-a0d4-427f-b52f-3eafd33530cb</webElementGuid>
    </webElementProperties>
</WebElementEntity>