<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c3fb7950-aaa6-448e-833f-eefb88818448</elementGuidId>
    <imagePath></imagePath>
    <name>link_Categories</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/header[1]/div[1]/div[6]/div[1]/a[7]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/ebooks/?_encoding=UTF8&amp;ref_=sv_kinc_6') and equals(@text,'Categories')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Categories, You are currently"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/ebooks/?_encoding=UTF8&amp;ref_=sv_kinc_6</value>
        <webElementGuid>7c7e3121-54d2-43c2-888f-abc7e5182be3</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Categories</value>
        <webElementGuid>7c7e3121-54d2-43c2-888f-abc7e5182be3</webElementGuid>
    </webElementProperties>
</WebElementEntity>