<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1e4f61df-ea79-4494-828d-9f6d4edcc2b5</elementGuidId>
    <imagePath></imagePath>
    <name>link_ActionAndAdventure</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/header[1]/div[1]/div[3]/div[17]/div[2]/div[1]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/b?node=1637004031&amp;ref_=sub_ebooks_cat_1') and equals(@text,'Action and Adventure')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Primary"i &gt;&gt; internal:role=link[name="Action and Adventure"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/b?node=1637004031&amp;ref_=sub_ebooks_cat_1</value>
        <webElementGuid>7c7e3121-54d2-43c2-888f-abc7e5182be3</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Action and Adventure</value>
        <webElementGuid>7c7e3121-54d2-43c2-888f-abc7e5182be3</webElementGuid>
    </webElementProperties>
</WebElementEntity>