<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>06f3ed2c-71e8-4163-9379-6ab7ea278ca0</elementGuidId>
    <imagePath></imagePath>
    <name>link_diamondCraftUnisexTShirtKidsBoyDpB0dy</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/span[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/Diamond-Craft-Unisex-T-Shirt-Kids-BOY/dp/B0DYVM2R3M/ref=zg_bsms_g_apparel_d_sccl_1/261-4519587-9490508?psc=1')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#p13n-asin-index-0 a &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/Diamond-Craft-Unisex-T-Shirt-Kids-BOY/dp/B0DYVM2R3M/ref=zg_bsms_g_apparel_d_sccl_1/261-4519587-9490508?psc=1</value>
        <webElementGuid>bb88ba4e-f2ba-49f8-ae42-3ec1acc2cec8</webElementGuid>
    </webElementProperties>
</WebElementEntity>