<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0a1f748a-54fb-4a50-b3df-7fed5291dc42</elementGuidId>
    <imagePath></imagePath>
    <name>link_NewReleases</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[2]/div[2]/ul[1]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/gp/new-releases/?ref_=nav_em_cs_newreleases_0_1_1_3') and equals(@text,'New Releases')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="New Releases"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/gp/new-releases/?ref_=nav_em_cs_newreleases_0_1_1_3</value>
        <webElementGuid>e26a3569-a0d4-427f-b52f-3eafd33530cb</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>New Releases</value>
        <webElementGuid>e26a3569-a0d4-427f-b52f-3eafd33530cb</webElementGuid>
    </webElementProperties>
</WebElementEntity>