<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5a7e0f3d-5bcb-459c-b388-621b280000bf</elementGuidId>
    <imagePath></imagePath>
    <name>link_BestSellerGrocery</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[3]/div[1]/div[1]/div[1]/div[4]/div[1]/span[1]/div[1]/div[1]/div[2]/span[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/ALPINO-Peanut-Chocolate-Protein-Gluten-Free/dp/B0BL3MTSSB/ref=lp_10894230031_1_1?pf_rd_p=9e034799-55e2-4ab2-b0d0-eb42f95b2d05&amp;pf_rd_r=6XTR7D0BXMN3DEDPDRR9&amp;sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>span &gt;&gt; internal:has-text="Best sellerin GroceryALPINO"i &gt;&gt; internal:role=link &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/ALPINO-Peanut-Chocolate-Protein-Gluten-Free/dp/B0BL3MTSSB/ref=lp_10894230031_1_1?pf_rd_p=9e034799-55e2-4ab2-b0d0-eb42f95b2d05&amp;pf_rd_r=6XTR7D0BXMN3DEDPDRR9&amp;sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D</value>
        <webElementGuid>e26a3569-a0d4-427f-b52f-3eafd33530cb</webElementGuid>
    </webElementProperties>
</WebElementEntity>